### ISSUE TITLE
RPTerm & PicoTerm

### ISSUE THREAD

**Issue by mchobby** [dquadros/RPTerm#1]
Hi Daniel,
This is not really an issue... but a request for advise regarding the PicoTerm project.
We already get in touch about development of PicoTerm for RC2014.
I'm working on the PicoTerm version (because it does fit my RC2014).

Presently the USB keyboard is not always detected at power up on the Picoterm Project. Unplug and plug again the USB keyboard does the trick. This behavior is ennoying.

I would like to know:
1) If RPTerm suffer of the same issue ?
2) If you find a way to solver it ?

Thank for your response.
Cheers,
Dominique

**Comment by dquadros** [comment]
short answer: RPTerm always detects my keyboard at power up, but I don't know if any of my changes affect that or if things behave different with other keyboards.

long answer: 

I did not have much time to work on RPTerm. I am very curious about what changes were made to PicoTerm to make it compatible with more keyboards, but a quick look to the now available sources came empty.

If I can find the time, I intend to do a more throughout analysis of the current PicoTerm code and update both my fork and RPTerm. Also on the list is to try a few different keyboards, and do some tests with PicoTerm. 

One last point: it may be a power issue, where the Pico cannot provide the needed voltage/current for the keyboard at power on, leaving the keyboard in some strange state.

**Comment by mchobby** [comment]
@dquadros 
I have implemented a delayed USB Power up line (5 sec) with a MOSFET and this is now working perfectly!

![Sélection_021](https://user-images.githubusercontent.com/2701466/208326542-0563854b-528a-4b35-a8be-42580a78b55e.png)

Thank for suggestion!
Dominique
